[custom.svn_revision]
description = "SVN Repository & Revision Indicator"
when = "svn --non-interactive info >/dev/null 2>&1"
command = "svn --non-interactive info --no-newline --show-item --revision 2>/dev/null"
symbol = "î‚ "
format = "[$symbol r$output](bold purple)"

[custom.svn_status]
when "svn --non-interactive info >/dev/null 2>&1"
description = "Symbol indicator of pending changes"
command = "$XDG_CONFIG_HOME/starship/svn_status.sh"
format = "[(\\[$output\\])](bold red)"
